#!/usr/bin/env ruby

# frozen_string_literal: true

require "bundler"
Bundler.setup(:default)

require "generathor"

require_relative "./lib/cli"

Generathor::Build.new(
  Generathor::Build::Config.new(
    command_name: "dev", 
    command_path: File.expand_path("./command/dev.json"), 
    lib_path: File.expand_path("./lib/cli"),
    lib_namespace: "Cli::Command",
    bin_path: File.expand_path("./bin"),
    zshrc_path: "#{Dir.home}/.zshrc"
  )
).build
